### ISSUE TITLE
clang-format for windows installation

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#116]
See [this page](https://www.dynamsoft.com/codepool/vscode-format-c-code-windows-linux.html)

### __Instruction__
How to Install Clang-Format on Windows
Download [Clang for Windows](https://releases.llvm.org/download.html).

Install the package and add the path of %LLVM% \bin to your system environment.

The shortcut Alter+Shift+F now works in Visual Studio Code for Windows.

**Comment by pr4deepr** [comment]
The instructions are same as you said, but when adding the path to your system environment, you need to specify it explicitly.
For example:
* Install Clang from link above.
* After installation, click Start and start typing "environment variables" in the search and you'll get this:
![image](https://user-images.githubusercontent.com/13831458/203806287-f573d1b0-8f7a-404a-8ad4-bd5a1004186c.png)

* Click on "Edit the System Environment Variables". 
* Select Ënvironment Variables:
![image](https://user-images.githubusercontent.com/13831458/203806740-fa8e83a7-63f5-4afc-a7e1-034f7038008c.png)

* Go to the "System Variables" and double click on "Path".
![image](https://user-images.githubusercontent.com/13831458/203806978-89f2ac9a-6f84-40a5-a8db-3e93bdf49317.png)

* Click on "New" and enter the path to your LLVM installation. In this case, it was: C:\Program Files\LLVM\bin
![image](https://user-images.githubusercontent.com/13831458/203807064-74ca42ae-7427-4cee-8773-e491524f711f.png)

*  
![image](https://user-images.githubusercontent.com/13831458/203807245-19e8034d-640b-44c1-967a-074cab9d2c8e.png)

Click Ok on all windows to save the Environment Variables. 

Restart Visual Studio Code and press Alt+Shift+F. 
VIsual Studio may ask you to confirm which formatter to use, for which you select "Clang-Format". 
![image](https://user-images.githubusercontent.com/13831458/203807810-a158e5d6-e986-49c7-a654-de9f70f0583e.png)

If you'd like to apply formatting everytime you save the file, set it do this under "Settings"using instructions [here](https://www.alphr.com/auto-format-vs-code/#:~:text=Click%20the%20%E2%80%9CSettings%E2%80%9D%20gear%20icon,%3A%20Format%20On%20Save%E2%80%9D%20option.).

**Comment by StRigaud** [comment]
Need to convert the issue into a markdown doc!
Thanks @pr4deepr !!!

**Comment by StRigaud** [comment]
No rush, I will organise the documentation folder with various help and doc needed for dev and users.
We will add it then.
I keep the issue open so that we can find it easily :)

**Comment by StRigaud** [comment]
# For Ubuntu:
```bash
sudo apt install clang-format
```

# For MacOS:

`clang-format` should automatically be installed with the c++ compiler `clang`.

```bash
xcode-select --install
```

To test if clang-format is installed, simply run the following command:
```bash
clang-format --version
```
