### ISSUE TITLE
Define default output-size of functions should be defined on CLIc level

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc_prototype#164]
On gateway level (e.g. in clij3 and pyclesperanto), a function might be called with `destination=None`. In that case, the output is automatically generated and should be of the right size. Default `destination` size is equivalent to the size of the first `source` (it was like that in pyclesperanto_prototype and clij/clij2). In case the output size/shape should be different from the input, we defined it like this:
* [in clij2](https://github.com/clij/clij2/blob/154150e60596e76f2b0773ef84691bebf5809f24/src/main/java/net/haesleinhuepf/clij2/plugins/MaximumZProjection.java#L55)
* [in pyclesperanto_prototype](https://github.com/clEsperanto/pyclesperanto_prototype/blob/efb38e99984b38ecf3141a63372989cee154958b/pyclesperanto_prototype/_tier1/_minimum_z_projection.py#L7)

We should now do something similar on C++ level because the output size/shape depends on given parameters only, not on Python/Java/... 

Ideas / questions:
* Would it be possible to automatically generate the destination buffer in case it's null when a kernel is called?
* Would it make sense that the [Execute()](https://github.com/clEsperanto/CLIc_prototype/blob/1f77c77215929bb4dfbe46bc45c37eabcc539788/clic/src/core/cleOperation.cpp#L135) function returns the destination buffer?
* We could then have the [...call()](https://github.com/clEsperanto/CLIc_prototype/blob/1f77c77215929bb4dfbe46bc45c37eabcc539788/clic/include/tier1/cleMaximumZProjectionKernel.hpp#L20) functions return the destination buffer

Just ideas; no action item yet :-)

**Comment by StRigaud** [comment]
Hey @haesleinhuepf 

Currently polishing this feature, it raise a question of enforcing specific types.

Current behavior:
- if user provide a `dst`, we do nothing and we try to execute the kernel with both `src` and `dst` provided by user
- if user does not provide a `dst` we create one using `src` info and type, and we adapt the shape to the kernel process.

Question now is should we enforce `dst` type and in which specific cases?

- Gaussian related kernel (Gaussian blur, DoG, etc.) -> enforce `float`?
- Binary related kernel (add, xor, and, threshold, etc.) -> enforce `uint8`?
- Label related kernel (connected comp, etc.) -> enforce `uint64`, or `uint32`?
- other?

FYI: 
at current day, `uint64` and `int64` are not compatible with `cl_image` nor with the CUDA build (unknown reason, to be investigated). This make me want to use `uint32` for label type even though it is more limited than `uint64`

**Comment by StRigaud** [comment]
This was introduce with the 0.7.0

CLIc function call now return the output as a pointer, and output variable in the parameter can be set as `nullptr`.
