### ISSUE TITLE
add documentation

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#178]
There is so far no documentation in the code on how to use functions and what they do.

Ideally we want to setup a doxygen (alternative is also possible) for each functions which details the following features:
- name
- parameter : name, type, default value
- return : type, 
- categories : list of strings
- priority : value (what is it?)
- resume : what does it do
- url : clij documentation

The documentation should be standardized for the functionalities to be easily portable to the Java and Python wrapper, as well as be used for auto-generation

**Comment by StRigaud** [comment]
I set a PR for documentation using doxygen:
- #183 

This setup a documentation build with the cmake option BUILD_DOCUMENTATION (default is ON).
And I made two example of doc block for some tier1 functions [here](https://github.com/clEsperanto/CLIc_prototype/blob/35fb565d852367eecdb7c6286acbae8d69c3c901/clic/include/tier1.hpp#L15C1-L27C3)

```cpp
/**
 * @name absolute
 * @brief Compute the absolute value of each pixel value x in a given image.
 * @category 'filter', 'in assistant'
 *
 * @param device Device::Pointer
 * @param src Array::Pointer
 * @param dst Array::Pointer (=nullptr)
 *
 * @return Array::Pointer
 *
 * @link https://clij.github.io/clij2-docs/reference_absolute
 */
```

OR

```cpp
/**
 * @name add_images_weighted
 * @brief Computes the sum of pairs of pixels x and y from images X and Y weighted with factors a and b.
 * @category 'combine', 'in assistant'
 *
 * @param device Device::Pointer
 * @param src0 Array::Pointer
 * @param src1 Array::Pointer
 * @param dst Array::Pointer (=nullptr)
 * @param factor0 float (=1.0)
 * @param factor1 float (=1.0)
 *
 * @return Array::Pointer
 *
 * @link https://clij.github.io/clij2-docs/reference_addImagesWeighted
 */
```

Questions:
- add an authors field: most of the kernels comes from clij but a few a now getting added by other collaborators.
- default value: may be a cleaner way to do so?
- brief: here brief a short, what if we have a more complex brief field? 
- alternative to doxygen?
- missing field?

WARNING:
As the auto generation would depend on the documentation, it will be very important that it corresponds properly to code and that no discrepancies happens during future development.

**Comment by StRigaud** [comment]
After a quick local test, no issue with a more complex brief descriptions, nor default values parsing.

@haesleinhuepf  (:wave:) if you have any feed back on the topic before we start writing the doc, that would be great

**Comment by haesleinhuepf** [comment]
> * add an authors field: most of the kernels comes from clij but a few a now getting added by other collaborators.

I'd say we could track authorship using git history. Thus, I would not duplicate this information in the code (even though I did so earlier).

Otherwise it looks pretty clear to me!

**Comment by haesleinhuepf** [comment]
Note to self: I should help on this branch: https://github.com/clesperanto/clic_prototype/tree/doxygen

I will add documentation to < 10 functions from tier3/4 to see if fields are missing

**Comment by haesleinhuepf** [comment]
One more note to myself: do this!

**Comment by StRigaud** [comment]
We could maybe add a field with the suggested data type to use for the documented filter?
e.g. gaussian_blur should use float type
e.g. binary_or should use uint8 type
etc.

**Comment by StRigaud** [comment]
the doxygen blocks become now the source for the code autogenerator for python (and java on the long run i guess).
It is now **IMPORTANT** to respect the format!
