### ISSUE TITLE
What if `src` and `dst` are the same when calling a kernel?

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#185]
Quick behavior question on what happen in OpenCL (or CUDA?) if your input and output are the same data.
e.g.:
```cpp
cle::tier1::gaussian_blur(device, data1, data1, sigma_x=3, sigma_y=3, sigma_z=3);
```
@haesleinhuepf  :wave:

**Comment by thawn** [comment]
I just tried it with the prototype and I got the same result if I used the source image as destination or if I used a new image as destination. See the attached notebook.
[test.ipynb.zip](https://github.com/clEsperanto/CLIc_prototype/files/12684613/test.ipynb.zip)

@StRigaud maybe you could run the notebook with the clic backend and check if the result is the same?

**Comment by StRigaud** [comment]
Yes I have the same results too, although I am also wandering about possible bad behaviour of doing this.
- Guassian works, but I assume other function may not like it
- Modification of the input
- other?

I ask this because I am thinking about data slicing and creating sub buffer view for region processing.
This can be done using the `clCreateSubBuffer()` from OpenCL which return a sub pointer of a buffer region.

This means that I could run a Gaussian blur a sub-region or do any other kind of kernel operation, however this I have yet to determine how to manage the `output` procedure in this case:
- giving the sub-buffer as input and output
- saving the result in a new output buffer and then copy it back into the original buffer. 
- other?

thanks for the feedback @thawn :)

**Comment by thawn** [comment]
>Guassian works, but I assume other function may not like it

if the input was modified in-place, I would expect that also the output of a gaussian blur is different. For example, if the first pixel used to be a 1 and then is replaced by 2.4, before the gaussian blur of the second pixel is calculated, that should affect the result of the gaussian for the second pixel etc.

**Comment by StRigaud** [comment]
I guess this is not happening because in the test case, the entire data fit the available computational ressources.

But we would see this type of errors if the data size is bigger than the GPU threats.

**Comment by StRigaud** [comment]
Question is voided.

`clCreateSubBuffer` only works in 1D. So it is not direct usable for our application. sub buffer processing will have to go through temporary buffer creation and sub region data copy, read, and write

for example, sub region processing will have to follow this pattern:
1. create subA
2. copy A region into subA
3. create subB
4. call kernel(subA, subB)
5. copy subB into A region
