### ISSUE TITLE
Release API and different OpenCL version

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#23]
So far most OpenCL version works all together with an exception of the clCreateCommandQueue() which is deprecated in the v2 to be replaced by clCreateCommandQueueWithProperties().

Hence, does a release compiled version of the API done with OpenCL 2.2 will work on a system running 1.2 (or reverse...). Or do we need to manage a release for both.

**Comment by haesleinhuepf** [comment]
Good question. I'd rather say a release for 1.2 works on all platforms. On the python side I saw pyopencl with OpenCL-2.0 support crashing on NVidia cards which usually come only with support for 1.2 (on Windows).

Thus, release a binary only for 1.2?

**Comment by StRigaud** [comment]
So, this should be solved by #35 with the `#define CL_HPP_TARGET_OPENCL_VERSION 120`

We defined the 1.2 as the default build. 

Thus it would be good to actually test if it work properly and add an option to change the version should be given at CMake configuration.
