### ISSUE TITLE
replace cl2.hpp by opencl.hpp

### ISSUE THREAD

**Issue by tropf** [clEsperanto/CLIc_prototype#37]
During building I frequently encountered

```
#pragma message("cl2.hpp has been renamed to opencl.hpp to make it clear that it supports all versions of OpenCL. Please include opencl.hpp directly.")
```

This is at least annoying; if it is harmful I can't tell (I suppose not).
I have done no research whether and how this could and should be mitigated.

Built on Debian Testing
```
$ apt show opencl-clhpp-headers
Package: opencl-clhpp-headers
Version: 3.0~2.0.13-1
```

**Comment by StRigaud** [comment]
This is a recent change from [OpenCL-clhpp](https://github.com/KhronosGroup/OpenCL-CLHPP) were they replace the include filename from cl2 to opencl for better code comprehension. Not harmful at all, just annoying ;)

We need to update the line `#include <cl2.hpp>` to `#include <opencl.hpp>`. Though I still need to test the [OpenCL-clhpp](https://github.com/KhronosGroup/OpenCL-CLHPP) installation on the different systems.

No issues on Linux with the apt package, but I haven't tested on Windows and MacOS yet.

**Comment by StRigaud** [comment]
#39 should fix this issue
