### ISSUE TITLE
Which datatype is allowed in buffer and images?

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#46]
I don't know if it is specific to CLIc or not.

Currently working on extending CLIc tests, I generated a script which apply a simple operation (e.g. add_image_and_scalar.cl) with buffers of different types (float, int, unsigned int, etc.). The current sources for the test can be found [here](https://github.com/StRigaud/CLIc_prototype/blob/master/clic/tests/types_test.cpp).

The title is of course a spoiler:
Operation on buffer of float as no issue.
Operation on buffer of char and unsigned char as no issue.
Operation on buffer of int, unsigned int return weird results.

for the first elements in the output buffer max out, either 327690 or 655350 and then the rest of the output buffer at 0.

I am thinking of an issue of type conversion or bit-size conversion during the execution, between the float parameter and the buffer data type. Something like values not occupying the same space in GPU. 
Or I am missing something ... Like I do not see int our unsigned int in the **Pixel type definition** of [CLIJ](https://github.com/clEsperanto/clij-opencl-kernels), nor in the **Two dimensional input image type definition**. 

EDIT:
I haven't tested other operation, I think the issue here is the presence of a float parameter.

EDIT2:
A quick test with absolute operation fail also with buffer of int ...

**Comment by haesleinhuepf** [comment]
Hi @StRigaud ,

I know how to fix this one 😃 It's likely the same bug as fixed here: https://github.com/clij/clij-clearcl/commit/a49049b9f75d4ddd6f1a3af0176645a261efb70c

I'm happy to do it... at some point in August 😁

Cheers,
Robert

**Comment by StRigaud** [comment]
So it is not a bug but a choice of implementation :smirk: ! 

> I'm happy to do it... at some point in August

No worries, it does not really impact me or any processing. As I was trying to extend coverage I was afraid that it was some deep implementation bug that I did saw before.
