### ISSUE TITLE
Organising kernels, headers and files alphabetically

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc_prototype#9]
Hi @StRigaud , hi future self,

I'm just adding some kernels and realised that it would be helpful to have all kinds of lists alphabetically to keep track of what's there and what not, e.g. the [kernel list](https://github.com/clEsperanto/CLIc_prototype/blob/master/include/cleKernelList.h). We might also auto-generate these lists at some point. 

:-)

Cheers,
Robert

**Comment by StRigaud** [comment]
So, auto-generation of kernel list could be manage by CMake at project generation type if we reorganize the project architecture and kernels filenames respect a template.

Architecture reshape is something that I will need soon as I am starting to getting lost in between the sources, and follow the core/tier1/tier2/etc. already used in other clEsperanto is a way.

**Comment by StRigaud** [comment]
I have reshaped the structure to fit the Tiers introduce on the Python side. I just changed a few things on my side for coherence.

Tier0 is renamed Core. It stores all basic classes of the library kernel, buffer, etc. , basic operations like pull push etc. and all classes that is not directly usable which include separable kernel and execute separable kernel. I also contain the Gateway class CLE but this could be move else where.
Tier1 and so on should then mimic the Python side.

I have also introduce Python script execution at build time for generating opencl kernel code in header file. This works like a charm. I will see to extend it for more code generation (aka KernelList.h, and other if possible)

**Comment by haesleinhuepf** [comment]
> I have also introduce Python script execution at build time for generating opencl kernel code in header file.

Wow! That sounds amazing! 🤩 Does that mean you're already working with a functional python wrapper?

**Comment by StRigaud** [comment]
> Does that mean you're already working with a functional python wrapper?

Sorry, not yet! For now it is just an execution of some python script when someone build the library. I use it to convert .cl files into .h headers but this will allows us to do more auto-generation of files like [cleKernelList.h](https://github.com/clEsperanto/CLIc_prototype/blob/master/clic/includes/core/cleKernelList.h) or other very repetitive files.

Wrapper is soon on my todo list though but I need to learn of this works, try, fail, learn more, try again, fail again, try again, etc ! :grimacing:
