### ISSUE TITLE
Question: What's the type of width/height/depth?

### ISSUE THREAD

**Issue by haesleinhuepf** [clEsperanto/CLIc_prototype#92]
In clesperantoj, we're currently handling image width/height/depth as `int`. In CLIJ / ClearCL those are of type `long`. I'm wondering what we use here. According to [code](https://github.com/clEsperanto/CLIc_prototype/blob/master/clic/include/core/cleObject.hpp#L96) it's `size_t`, which [appears to be an `unsigned integer`](https://cplusplus.com/reference/cstring/size_t/). I'm wondering if we could handle a 1D image of 6 GB like this. This was tricky with CLIJ and that's why I'm raising this question here.

**Comment by StRigaud** [comment]
Currently in CLIc, shape dimensions are hold in a `size_t`. This type is redefine as the biggest unsigned integer possible on your system, which in most cases now should be equivalent of `uint64`.

I do not know what was the limitation in CLIJ, but on my side, if it fit the memory I can do it.

Also, for clarity, I am replacing most in-code native type name (int, char, short, float) by a more type size explicit name in
```
         char  int8_t
         short int16_t
         int   int32_t
unsigned char  uint8_t
unsigned short uint16_t
unsigned int   uint32_t
```
This is more correct for image manipulation and calculation, as well as make it easier to read and understand than a `unsigned long long`

**Comment by haesleinhuepf** [comment]
CLIJ was limited to Java type unsigned long (uint64). Does anything speak against that? The system cannot address usigned long long anyway... If that's ok, I would go for it in clesperantoJ.
