### ISSUE TITLE
Detect Maxima/Minima

### ISSUE THREAD

**Issue by StRigaud** [clEsperanto/CLIc_prototype#96]
I have two issues with this kernel:

First one is API wise.
By default the kernel search around pixel with a box radius=1 neighborhood. This is setup in the OpenCL kernel code. No radius or similar allowing to explore larger neighborhood. This is relegated to a mean kernel filter applied a head of the detection when calling the operation.
```
cle.DetectMaxima(input, output, 3, 3, 3)
{
  Mean(input, output, 3,3,3)
  Copy(output, input)
  DetectMaxima(input, output)
}
```
Hence if we want to search for a neighborhood of 1, we need to set the radius to 0, and if we want to search for neighborhood of 4 we need to set the radius to 3. This is how I understand it :thinking: 

Second one is algorithmic.
The use of the mean operator spread the maxima signal, creating plateau. Hence this introduce a shift in the maxima detection position equal (in simple cases) to the radius.
Should not create too much issue if nobody raised this, but the detect will start failing or doing weird things if we start using large radius value.

Wondering then if their is not a smarter way to do this:

- A double pass detection for example, first detecting all peaks, second only keeping highest in a specified radius?
- Introduce a radius parameter in the kernel?

I'm guessing these solutions are slower though. 
@haesleinhuepf? what do you think?

**Comment by StRigaud** [comment]
Adding also the issue of detection failing if maxima/minima is located along any x=0,y=0, or z=0 coordinate, voiding half of the data in 3D image with depth=2.
I save it here because I just got stuck again on this bug ...

**Comment by haesleinhuepf** [comment]
I need to fix that also on CLIJ and pyclesperanto_prototype

**Comment by StRigaud** [comment]
There was still an issue in our first fix.

Look at what I did on the clesperanto_kernel version I pushed [here](https://github.com/clEsperanto/clij-opencl-kernels/blob/clesperanto_kernels/kernels/detect_maxima.cl#L24)

basically I know skip the central pixel. Work like a charm on my side.

**Comment by StRigaud** [comment]
I will remove the mean filter with the new version coming and close this issues.
We will also need to fix detect minima and the slide by slide version of those filters.
