### ISSUE TITLE
Implement Object Print

### ISSUE THREAD

**Issue by aaron-bray** [clEsperanto/CLIc_prototype#98]
It would be helpful for the cle::Object to have its << operator implemented.
This is helpful to view states/use with in pipline processes

**Comment by StRigaud** [comment]
Thanks for the feedback,

This has been added with the incoming version.
- https://github.com/clEsperanto/CLIc_prototype/pull/94/commits/41bdf312a5e31b17266f2cdde23a3175a7206d54

All data class and kernel operation class will have now both `ToString()` and `<<operator()` implemented

**Comment by aaron-bray** [comment]
Thanks!

Looking forwart to testing it out
